{
 "title": "UrBackup Exporter",
 "description": "UrBackup dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Last backup",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urbackup_backup_lasttime{backup_type=\"file\"} * 1000",
     "legendFormat": "{{client_name}}"
    },
    {
     "expr": "time() - urbackup_backup_lasttime{backup_type=\"file\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Last backup status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urbackup_backup_ok{backup_type=\"file\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "urbackup_client_online", "legendFormat": "{{client_name}}" }
   ]
  },
  {
   "title": "Total backup size",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_size_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total backup count",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_number_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client details",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urbackup_backup_lasttime{backup_type=\"file\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total backup size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_size_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total backup count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_number_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client status (online)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(client_name)(urbackup_client_online)",
     "legendFormat": "{{client_name}}"
    }
   ]
  }
 ]
}